version: 0.2

env:
  parameter-store:
    BUILD_SSH_KEY: "/otel-grpc-healthcheck/private_deploy_key"
    GIT_EMAIL: "/otel-grpc-healthcheck/git_email"
    GIT_USERNAME: "/otel-grpc-healthcheck/git_username"

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "${BUILD_SSH_KEY}" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >> ~/.ssh/known_hosts
      - eval "$(ssh-agent)"
  pre_build:
    commands:
      - git clone --branch "generate-otel-version" "git@github.com:jammymalina/otel-grpc-healthcheck.git" .
      - git config --global user.email "${GIT_EMAIL}"
      - git config --global user.name "${GIT_USERNAME}"
  build:
    commands:
      - test -n "${VERSION}"
      - ./generate_new_version.sh "${VERSION}" "${COMPONENT_VERSION}"
      - echo "New version was generated and pushed to the repository"
