allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-codebuild@3.1053.0 || 3.1133.0'
  - '@aws-sdk/client-ssm@3.1053.0 || 3.1133.0'
  - '@types/node@26.6.0'
onlyBuiltDependencies:
  - esbuild
